# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Add nuget to PATH
      uses: nuget/setup-nuget@v1

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Nuget Restore
      working-directory: ConsoleAppForTest
      run: nuget restore ConsoleAppForTest.sln

    - name: Build
      working-directory: ConsoleAppForTest
      run: msbuild ConsoleAppForTest.sln

    - name: Test
      working-directory: ConsoleAppForTest.Tests\bin\debug\
      run: vstest.console.exe ConsoleAppForTest.Tests.dll

    # - name: Test
    #   working-directory: ConsoleAppForTest
    #   run: '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe"'

